### ISSUE TITLE
Fontain take more than 10 seconds to initialize on Android 4.4

### ISSUE THREAD

**Issue by vfongmala** [scopely/fontain#5]
As title, I tried to use Fontain on Android 4.4.x but It takes more than 10 seconds to initialize library. Please check on this issue.

**Comment by PeterAttardo** [comment]
I just measured the example app on an Android 4.4.4 emulator and it initialized in 172 milliseconds. Can you provide more details on your particular implementation? Are you using a large number of fonts?

If possible, see if you can use the method tracer and identify specific method calls that seem to be taking an inordinately long time: https://developer.android.com/studio/profile/am-methodtrace.html
